### ISSUE TITLE
Can not connect to BigQuery via Ibis server

### ISSUE THREAD

**Issue by onlyjackfrost** [Canner/wren-engine#551]
ibis server error message
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/canner/wren-engine/ibis-server/routers/ibis.py", line 23, in query
    return to_json(data_source.get_connection(dto).sql(dto.sql).to_pandas())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/ibis/backends/sql/__init__.py", line 200, in sql
    schema = self._get_schema_using_query(query)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/ibis/backends/bigquery/__init__.py", line 595, in _get_schema_using_query
    job = self.client.query(
          ^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/google/cloud/bigquery/client.py", line 3483, in query
    return _job_helpers.query_jobs_insert(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/google/cloud/bigquery/_job_helpers.py", line 158, in query_jobs_insert
    future = do_query()
             ^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/google/cloud/bigquery/_job_helpers.py", line 135, in do_query
    query_job._begin(retry=retry, timeout=timeout)
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py", line 1374, in _begin
    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 740, in _begin
    api_response = client._call_api(
                   ^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/google/cloud/bigquery/client.py", line 831, in _call_api
    return call()
           ^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.11.1/lib/python3.11/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/wrenai/jobs?prettyPrint=false: Syntax error: Unexpected string literal "wrenai" at [3:3]

Location: None
Job ID: 85eaaa7e-20b4-404e-9363-a17c82e96453
```

I've compare the origin credential file with the credential decoded from base64 string, its the same.

@grieve54706 can you help me with this?

**Comment by grieve54706** [comment]
Could you provide the SQL and connection info?

**Comment by onlyjackfrost** [comment]
I found that I entered the wrong SQL statement.
Everything works fine after correcting the SQL statement
