### ISSUE TITLE
Fail to parse "from" column

### ISSUE THREAD

**Issue by imAsterSun** [Canner/wren-engine#640]
The column named "from" in the mdl will cause engine parse issue
```
2024-06-28 10:55:23 2024-06-28T02:55:23.595Z    WARN    ForkJoinPool.commonPool-worker-29       io.wren.main.web.WrenExceptionMapper    Exception, type: class java.util.concurrent.CompletionException, message: java.lang.RuntimeException: Failed to parse expression: from
2024-06-28 10:55:23 java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to parse expression: from
2024-06-28 10:55:23     at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
2024-06-28 10:55:23     at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
2024-06-28 10:55:23     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
2024-06-28 10:55:23     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
2024-06-28 10:55:23     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
2024-06-28 10:55:23     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
2024-06-28 10:55:23     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
2024-06-28 10:55:23     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
2024-06-28 10:55:23     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2024-06-28 10:55:23 Caused by: java.lang.RuntimeException: Failed to parse expression: from
2024-06-28 10:55:23     at io.wren.base.sqlrewrite.Utils.parseExpression(Utils.java:77)
2024-06-28 10:55:23     at io.wren.base.sqlrewrite.WrenDataLineage.getSourceColumns(WrenDataLineage.java:312)
2024-06-28 10:55:23     at io.wren.base.sqlrewrite.WrenDataLineage.collectSourceColumns(WrenDataLineage.java:148)
2024-06-28 10:55:23     at io.wren.base.sqlrewrite.WrenDataLineage.<init>(WrenDataLineage.java:73)
2024-06-28 10:55:23     at io.wren.base.sqlrewrite.WrenDataLineage.analyze(WrenDataLineage.java:67)
2024-06-28 10:55:23     at io.wren.base.AnalyzedMDL.<init>(AnalyzedMDL.java:32)
2024-06-28 10:55:23     at io.wren.main.PreviewService.lambda$dryPlan$1(PreviewService.java:102)
2024-06-28 10:55:23     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
2024-06-28 10:55:23     ... 6 more
2024-06-28 10:55:23 Caused by: io.trino.sql.parser.ParsingException: line 1:1: mismatched input 'from'. Expecting: <expression>
2024-06-28 10:55:23     at io.trino.sql.parser.ErrorHandler.syntaxError(ErrorHandler.java:109)
2024-06-28 10:55:23     at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
2024-06-28 10:55:23     at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
2024-06-28 10:55:23     at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
2024-06-28 10:55:23     at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
2024-06-28 10:55:23     at io.trino.sql.parser.SqlBaseParser.booleanExpression(SqlBaseParser.java:10480)
2024-06-28 10:55:23     at io.trino.sql.parser.SqlBaseParser.expression(SqlBaseParser.java:10056)
2024-06-28 10:55:23     at io.trino.sql.parser.SqlBaseParser.standaloneExpression(SqlBaseParser.java:353)
2024-06-28 10:55:23     at io.trino.sql.parser.SqlParser.invokeParser(SqlParser.java:145)
2024-06-28 10:55:23     at io.trino.sql.parser.SqlParser.createExpression(SqlParser.java:90)
2024-06-28 10:55:23     at io.wren.base.sqlrewrite.Utils.parseExpression(Utils.java:74)
2024-06-28 10:55:23     ... 13 more
2024-06-28 10:55:23 Caused by: org.antlr.v4.runtime.InputMismatchException
2024-06-28 10:55:23     at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:270)
2024-06-28 10:55:23     at io.trino.sql.parser.SqlBaseParser.booleanExpression(SqlBaseParser.java:10192)
2024-06-28 10:55:23     ... 18 more
```

**Comment by goldmedal** [comment]
Thanks @imAsterSun for reporting this issue.

I tested the column named `from`:
```json
          {
            "name": "from",
            "type": "varchar",
          },
```
It works well.

If your column in the data source side called `from` and you use it in the column expression like
```json
          {
            "name": "from",
            "expression": "from",
            "type": "varchar",
          },
```
You should add quotes for it like
```json
          {
            "name": "from",
            "expression": "\"from\"",
            "type": "varchar",
          },
```

**Comment by imAsterSun** [comment]
@goldmedal  Thanks for the reply! This solution works on the scenario 🙏

**Comment by goldmedal** [comment]
I thinks this issue has been solved. Let's close it.
