### ISSUE TITLE
TrinoContainer may encounter empty nodes

### ISSUE THREAD

**Issue by grieve54706** [Canner/wren-engine#671]
Trino version 450.

After starting the TrinoContainer, we may encounter this error when sending a SELECT statement.
```
2024-07-15 17:15:28 2024-07-15T09:15:28.165Z    INFO    main    io.trino.server.Server  ======== SERVER STARTED ========
2024-07-15 17:15:28 2024-07-15T09:15:28.882Z    INFO    dispatcher-query-3      io.trino.event.QueryMonitor     TIMELINE: Query 20240715_091528_00000_8ufrr :: FINISHED :: elapsed 406ms :: planning 121ms :: waiting 36ms :: scheduling 244ms :: running 32ms :: finishing 9ms :: begin 2024-07-15T09:15:28.446Z :: end 2024-07-15T09:15:28.852Z
2024-07-15 17:15:29 2024-07-15T09:15:29.207Z    INFO    dispatcher-query-3      io.trino.event.QueryMonitor     TIMELINE: Query 20240715_091529_00001_8ufrr :: FINISHED :: elapsed 32ms :: planning 0ms :: waiting 1ms :: scheduling 32ms :: running 0ms :: finishing 32ms :: begin 2024-07-15T09:15:29.172Z :: end 2024-07-15T09:15:29.204Z
2024-07-15 17:15:29 2024-07-15T09:15:29.711Z    INFO    dispatcher-query-1      io.trino.event.QueryMonitor     TIMELINE: Query 20240715_091529_00002_8ufrr :: FINISHED :: elapsed 476ms :: planning 291ms :: waiting 142ms :: scheduling 168ms :: running 12ms :: finishing 5ms :: begin 2024-07-15T09:15:29.232Z :: end 2024-07-15T09:15:29.708Z
2024-07-15 17:15:29 2024-07-15T09:15:29.751Z    INFO    dispatcher-query-1      io.trino.event.QueryMonitor     TIMELINE: Query 20240715_091529_00003_8ufrr :: FINISHED :: elapsed 16ms :: planning 0ms :: waiting 0ms :: scheduling 16ms :: running 0ms :: finishing 16ms :: begin 2024-07-15T09:15:29.734Z :: end 2024-07-15T09:15:29.750Z
2024-07-15 17:15:29 2024-07-15T09:15:29.965Z    INFO    dispatcher-query-0      io.trino.event.QueryMonitor     TIMELINE: Query 20240715_091529_00004_8ufrr :: FAILED (GENERIC_INTERNAL_ERROR) :: elapsed 175ms :: planning 175ms :: waiting 0ms :: scheduling 0ms :: running 0ms :: finishing 0ms :: begin 2024-07-15T09:15:29.788Z :: end 2024-07-15T09:15:29.963Z
```
```
2024-07-16 10:36:14 2024-07-16T02:36:14.189Z    DEBUG   dispatcher-query-6      io.trino.execution.StageStateMachine    Stage 20240716_023613_00003_wuree.0 is PLANNED
2024-07-16 10:36:14 2024-07-16T02:36:14.190Z    DEBUG   dispatcher-query-1      io.trino.execution.StageStateMachine    Stage 20240716_023613_00003_wuree.1 is PLANNED
2024-07-16 10:36:14 2024-07-16T02:36:14.190Z    DEBUG   dispatcher-query-3      io.trino.execution.QueryStateMachine    Query 20240716_023613_00003_wuree is STARTING
2024-07-16 10:36:14 2024-07-16T02:36:14.190Z    DEBUG   stage-scheduler io.trino.execution.scheduler.PipelinedStageExecution    Pipelined stage execution 20240716_023613_00003_wuree.0 is PLANNED
2024-07-16 10:36:14 2024-07-16T02:36:14.190Z    DEBUG   stage-scheduler io.trino.execution.scheduler.PipelinedStageExecution    Pipelined stage execution 20240716_023613_00003_wuree.1 is PLANNED
2024-07-16 10:36:14 2024-07-16T02:36:14.194Z    DEBUG   dispatcher-query-7      io.trino.execution.QueryStateMachine    Query 20240716_023613_00003_wuree is FAILED
2024-07-16 10:36:14 2024-07-16T02:36:14.194Z    DEBUG   Query-20240716_023613_00003_wuree-195   io.trino.execution.QueryStateMachine    Query 20240716_023613_00003_wuree failed
2024-07-16 10:36:14 java.lang.IllegalArgumentException: nodes is empty
2024-07-16 10:36:14     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
2024-07-16 10:36:14     at io.trino.execution.scheduler.FixedSourcePartitionedScheduler.<init>(FixedSourcePartitionedScheduler.java:71)
2024-07-16 10:36:14     at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.createStageScheduler(PipelinedQueryScheduler.java:1168)
2024-07-16 10:36:14     at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.create(PipelinedQueryScheduler.java:924)
2024-07-16 10:36:14     at io.trino.execution.scheduler.PipelinedQueryScheduler.createDistributedStagesScheduler(PipelinedQueryScheduler.java:320)
2024-07-16 10:36:14     at io.trino.execution.scheduler.PipelinedQueryScheduler.start(PipelinedQueryScheduler.java:303)
2024-07-16 10:36:14     at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:442)
2024-07-16 10:36:14     at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:272)
2024-07-16 10:36:14     at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:150)
2024-07-16 10:36:14     at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:134)
2024-07-16 10:36:14     at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:570)
2024-07-16 10:36:14     at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:545)
2024-07-16 10:36:14     at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1137)
2024-07-16 10:36:14     at io.trino.$gen.Trino_450____20240716_023608_2.run(Unknown Source)
2024-07-16 10:36:14     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2024-07-16 10:36:14     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2024-07-16 10:36:14     at java.base/java.lang.Thread.run(Thread.java:1570)
2024-07-16 10:36:14 
2024-07-16 10:36:14 
2024-07-16 10:36:14 2024-07-16T02:36:14.195Z    INFO    dispatcher-query-7      io.trino.event.QueryMonitor     TIMELINE: Query 20240716_023613_00003_wuree :: FAILED (GENERIC_INTERNAL_ERROR) :: elapsed 331ms :: planning 331ms :: waiting 0ms :: scheduling 0ms :: running 0ms :: finishing 0ms :: begin 2024-07-16T02:36:13.862Z :: end 2024-07-16T02:36:14.193Z
2024-07-16 10:36:14 2024-07-16T02:36:14.196Z    DEBUG   dispatcher-query-3      io.trino.execution.StageStateMachine    Stage 20240716_023613_00003_wuree.1 is ABORTED
2024-07-16 10:36:14 2024-07-16T02:36:14.196Z    DEBUG   dispatcher-query-8      io.trino.execution.StageStateMachine    Stage 20240716_023613_00003_wuree.0 is ABORTED
```

We attempted to execute `SELECT * FROM system.runtime.nodes` and `SHOW CATALOGS LIKE 'tpch'` before querying to ensure that the node was active and the 'tpch' catalog was ready. This issue may be related to a Trino discovery node problem. A similar issue was reported previously (see [trinodb/trino#13388](https://github.com/trinodb/trino/discussions/13388)).

**Comment by grieve54706** [comment]
Delay some time to wait for Trino to be ready seems so good.
https://github.com/Canner/wren-engine/blob/861f978df3438a1ba01d3518101de59bcffd1da8/ibis-server/tests/routers/v2/connector/test_trino.py#L77-L78
